In [11]:
from configparser import ConfigParser
import pandas as pd
import requests
from sportmonks.soccer import SoccerApiV2

In [12]:
parser = ConfigParser()

In [13]:
parser.read('../config.cfg')
token = parser.get('sportmonks', 'token')

In [14]:
query = f'https://soccer.sportmonks.com/api/v2.0/leagues?api_token={token}'
data = requests.get(query)

In [15]:
len(data.json()['data'])

34

In [16]:
api = SoccerApiV2(api_token=token)

In [6]:
team_data = api.teams(includes=['transfers'])

TypeError: teams() missing 1 required positional argument: 'season_id'

In [41]:
def download_teams_single_season(season_id, base_path='../data'):
    try:
        pd.DataFrame(api.teams(season_id, includes=['transfers'])).to_csv(f'{base_path}/teams_season_{season_id}.csv')
    except Exception as e:
        print(season_id)
        print(e)

def download_teams_single_league(league_name, base_path='../data'):
    leagues = pd.read_csv(base_path+'/leagues.csv')
    seasons = eval(leagues.loc[leagues['name'] == league_name]['seasons'].iloc[0])
    for season in seasons:
        download_teams_single_season(season['id'], base_path=base_path)
    
download_teams_single_league('La Liga')

[{'id': 2052, 'name': '2005/2006', 'league_id': 564, 'is_current_season': False, 'current_round_id': None, 'current_stage_id': None}, {'id': 2053, 'name': '2006/2007', 'league_id': 564, 'is_current_season': False, 'current_round_id': None, 'current_stage_id': None}, {'id': 2054, 'name': '2007/2008', 'league_id': 564, 'is_current_season': False, 'current_round_id': None, 'current_stage_id': None}, {'id': 2055, 'name': '2008/2009', 'league_id': 564, 'is_current_season': False, 'current_round_id': None, 'current_stage_id': None}, {'id': 2058, 'name': '2009/2010', 'league_id': 564, 'is_current_season': False, 'current_round_id': None, 'current_stage_id': None}, {'id': 2056, 'name': '2010/2011', 'league_id': 564, 'is_current_season': False, 'current_round_id': None, 'current_stage_id': None}, {'id': 2057, 'name': '2011/2012', 'league_id': 564, 'is_current_season': False, 'current_round_id': None, 'current_stage_id': None}, {'id': 2059, 'name': '2012/2013', 'league_id': 564, 'is_current_season': False, 'current_round_id': None, 'current_stage_id': None}, {'id': 2060, 'name': '2013/2014', 'league_id': 564, 'is_current_season': False, 'current_round_id': None, 'current_stage_id': None}, {'id': 2061, 'name': '2014/2015', 'league_id': 564, 'is_current_season': False, 'current_round_id': None, 'current_stage_id': None}, {'id': 2063, 'name': '2015/2016', 'league_id': 564, 'is_current_season': False, 'current_round_id': None, 'current_stage_id': None}, {'id': 853, 'name': '2016/2017', 'league_id': 564, 'is_current_season': False, 'current_round_id': None, 'current_stage_id': None}, {'id': 8442, 'name': '2017/2018', 'league_id': 564, 'is_current_season': False, 'current_round_id': None, 'current_stage_id': None}, {'id': 13133, 'name': '2018/2019', 'league_id': 564, 'is_current_season': False, 'current_round_id': None, 'current_stage_id': None}, {'id': 16326, 'name': '2019/2020', 'league_id': 564, 'is_current_season': True, 'current_round_id': 175869, 'current_stage_id': 77444988}]

In [18]:
team_data = pd.DataFrame(api.teams(2052, includes=['transfers']))

In [24]:
team_data[0]

{'id': 36,
 'legacy_id': 290,
 'name': 'Celta de Vigo',
 'short_code': 'CLV',
 'twitter': '@RCCelta',
 'country_id': 32,
 'national_team': False,
 'founded': 1923,
 'logo_path': 'https://cdn.sportmonks.com/images//soccer/teams/4/36.png',
 'venue_id': 9239,
 'current_season_id': 16326,
 'transfers': [{'player_id': 445429,
   'from_team_id': 36,
   'to_team_id': 5841,
   'season_id': 2063,
   'transfer': 'n/a',
   'type': 'OUT',
   'date': '2015-07-31',
   'amount': None},
  {'player_id': 445429,
   'from_team_id': 25817,
   'to_team_id': 36,
   'season_id': 2063,
   'transfer': 'n/a',
   'type': 'IN',
   'date': '2015-07-01',
   'amount': None},
  {'player_id': 445429,
   'from_team_id': 36,
   'to_team_id': 25817,
   'season_id': 2061,
   'transfer': 'loan',
   'type': 'OUT',
   'date': '2014-08-21',
   'amount': None},
  {'player_id': 445429,
   'from_team_id': 25779,
   'to_team_id': 36,
   'season_id': 2061,
   'transfer': 'n/a',
   'type': 'IN',
   'date': '2014-07-01',
   'amount': None},
  {'player_id': 335789,
   'from_team_id': 36,
   'to_team_id': 1012,
   'season_id': 2071,
   'transfer': 'n/a',
   'type': 'OUT',
   'date': '2011-07-18',
   'amount': None},
  {'player_id': 335789,
   'from_team_id': 7980,
   'to_team_id': 36,
   'season_id': 2070,
   'transfer': 'n/a',
   'type': 'IN',
   'date': '2010-08-12',
   'amount': None},
  {'player_id': 380453,
   'from_team_id': 36,
   'to_team_id': 13352,
   'season_id': 2060,
   'transfer': 'n/a',
   'type': 'OUT',
   'date': '2013-07-31',
   'amount': None},
  {'player_id': 380453,
   'from_team_id': 26517,
   'to_team_id': 36,
   'season_id': 2059,
   'transfer': 'n/a',
   'type': 'IN',
   'date': '2012-07-01',
   'amount': None},
  {'player_id': 380453,
   'from_team_id': 36,
   'to_team_id': 26517,
   'season_id': 2071,
   'transfer': 'loan',
   'type': 'OUT',
   'date': '2012-01-12',
   'amount': None},
  {'player_id': 1468,
   'from_team_id': 36,
   'to_team_id': 3468,
   'season_id': 2071,
   'transfer': 'sold',
   'type': 'OUT',
   'date': '2011-05-01',
   'amount': '1.5M'},
  {'player_id': 5907,
   'from_team_id': 36,
   'to_team_id': 931,
   'season_id': 2070,
   'transfer': 'free',
   'type': 'OUT',
   'date': '2010-07-01',
   'amount': None},
  {'player_id': 294,
   'from_team_id': 214,
   'to_team_id': 36,
   'season_id': 2052,
   'transfer': 'loan',
   'type': 'IN',
   'date': '2005-08-01',
   'amount': None},
  {'player_id': 186275,
   'from_team_id': 36,
   'to_team_id': 323,
   'season_id': 2061,
   'transfer': 'n/a',
   'type': 'OUT',
   'date': '2014-03-11',
   'amount': None},
  {'player_id': 186275,
   'from_team_id': 36,
   'to_team_id': 274,
   'season_id': 2070,
   'transfer': 'loan',
   'type': 'OUT',
   'date': '2011-01-16',
   'amount': None},
  {'player_id': 95736,
   'from_team_id': 36,
   'to_team_id': 7980,
   'season_id': 2063,
   'transfer': 'sold',
   'type': 'OUT',
   'date': '2016-01-04',
   'amount': '6.5M'},
  {'player_id': 95736,
   'from_team_id': 9904,
   'to_team_id': 36,
   'season_id': 2059,
   'transfer': 'bought',
   'type': 'IN',
   'date': '2012-08-09',
   'amount': '1.5M'},
  {'player_id': 1339,
   'from_team_id': 7980,
   'to_team_id': 36,
   'season_id': 2067,
   'transfer': 'loan',
   'type': 'IN',
   'date': '2007-08-01',
   'amount': None},
  {'player_id': 2817,
   'from_team_id': 36,
   'to_team_id': 236,
   'season_id': 2061,
   'transfer': 'n/a',
   'type': 'OUT',
   'date': '2014-08-15',
   'amount': None},
  {'player_id': 2817,
   'from_team_id': 36,
   'to_team_id': 3468,
   'season_id': 2059,
   'transfer': 'loan',
   'type': 'OUT',
   'date': '2012-08-31',
   'amount': None},
  {'player_id': 185578,
   'from_team_id': 36,
   'to_team_id': 13258,
   'season_id': 2061,
   'transfer': 'n/a',
   'type': 'OUT',
   'date': '2014-07-01',
   'amount': None},
  {'player_id': 185578,
   'from_team_id': 13258,
   'to_team_id': 36,
   'season_id': 2060,
   'transfer': 'loan',
   'type': 'IN',
   'date': '2013-08-22',
   'amount': None},
  {'player_id': 3704,
   'from_team_id': 36,
   'to_team_id': 109,
   'season_id': 8442,
   'transfer': 'n/a',
   'type': 'OUT',
   'date': '2017-07-01',
   'amount': None},
  {'player_id': 3704,
   'from_team_id': 109,
   'to_team_id': 36,
   'season_id': 853,
   'transfer': 'loan',
   'type': 'IN',
   'date': '2016-08-29',
   'amount': None},
  {'player_id': 704,
   'from_team_id': 2712,
   'to_team_id': 36,
   'season_id': 2053,
   'transfer': 'loan',
   'type': 'IN',
   'date': '2006-07-12',
   'amount': None},
  {'player_id': 446144,
   'from_team_id': 36,
   'to_team_id': 28088,
   'season_id': 2063,
   'transfer': 'n/a',
   'type': 'OUT',
   'date': '2015-09-19',
   'amount': None},
  {'player_id': 189240,
   'from_team_id': 36,
   'to_team_id': 103,
   'season_id': 8442,
   'transfer': 'n/a',
   'type': 'OUT',
   'date': '2017-07-01',
   'amount': None},
  {'player_id': 189240,
   'from_team_id': 618,
   'to_team_id': 36,
   'season_id': 853,
   'transfer': 'n/a',
   'type': 'IN',
   'date': '2016-07-05',
   'amount': None},
  {'player_id': 62324,
   'from_team_id': 1118,
   'to_team_id': 36,
   'season_id': None,
   'transfer': 'n/a',
   'type': 'IN',
   'date': '2018-07-01',
   'amount': None},
  {'player_id': 62324,
   'from_team_id': 1118,
   'to_team_id': 36,
   'season_id': 2061,
   'transfer': 'n/a',
   'type': 'IN',
   'date': '2015-01-09',
   'amount': None},
  {'player_id': 78,
   'from_team_id': 36,
   'to_team_id': 22,
   'season_id': 2069,
   'transfer': 'sold',
   'type': 'OUT',
   'date': '2009-08-13',
   'amount': '2M'},
  {'player_id': 78,
   'from_team_id': 830,
   'to_team_id': 36,
   'season_id': 2068,
   'transfer': 'free',
   'type': 'IN',
   'date': '2008-07-01',
   'amount': None},
  {'player_id': 3794,
   'from_team_id': 12,
   'to_team_id': 36,
   'season_id': 2067,
   'transfer': 'n/a',
   'type': 'IN',
   'date': '2008-02-12',
   'amount': None},
  {'player_id': 3794,
   'from_team_id': 36,
   'to_team_id': 12,
   'season_id': 2067,
   'transfer': 'loan',
   'type': 'OUT',
   'date': '2007-08-31',
   'amount': None},
  {'player_id': 185976,
   'from_team_id': 5855,
   'to_team_id': 36,
   'season_id': 2061,
   'transfer': 'free',
   'type': 'IN',
   'date': '2014-07-01',
   'amount': None},
  {'player_id': 185976,
   'from_team_id': 5855,
   'to_team_id': 36,
   'season_id': 2059,
   'transfer': 'loan',
   'type': 'IN',
   'date': '2012-07-16',
   'amount': None},
  {'player_id': 129060,
   'from_team_id': 109,
   'to_team_id': 36,
   'season_id': 853,
   'transfer': 'free',
   'type': 'IN',
   'date': '2016-07-12',
   'amount': None},
  {'player_id': 185519,
   'from_team_id': 8269,
   'to_team_id': 36,
   'season_id': 2071,
   'transfer': 'free',
   'type': 'IN',
   'date': '2011-07-01',
   'amount': None},
  {'player_id': 800,
   'from_team_id': 676,
   'to_team_id': 36,
   'season_id': 2063,
   'transfer': 'bought',
   'type': 'IN',
   'date': '2015-07-07',
   'amount': '5.3M'},
  {'player_id': 800,
   'from_team_id': 36,
   'to_team_id': 8,
   'season_id': 2060,
   'transfer': 'sold',
   'type': 'OUT',
   'date': '2013-07-01',
   'amount': '8.2M'},
  {'player_id': 185482,
   'from_team_id': 83,
   'to_team_id': 36,
   'season_id': 2060,
   'transfer': 'bought',
   'type': 'IN',
   'date': '2013-07-01',
   'amount': '1M'},
  {'player_id': 82841,
   'from_team_id': 9341,
   'to_team_id': 36,
   'season_id': 2063,
   'transfer': 'bought',
   'type': 'IN',
   'date': '2015-07-01',
   'amount': '3M'},
  {'player_id': 186450,
   'from_team_id': 83,
   'to_team_id': 36,
   'season_id': 2061,
   'transfer': 'n/a',
   'type': 'IN',
   'date': '2014-07-01',
   'amount': None},
  {'player_id': 6624,
   'from_team_id': 11,
   'to_team_id': 36,
   'season_id': 8442,
   'transfer': 'bought',
   'type': 'IN',
   'date': '2017-07-04',
   'amount': '3.5M'},
  {'player_id': 6624,
   'from_team_id': 36,
   'to_team_id': 11,
   'season_id': 8442,
   'transfer': 'n/a',
   'type': 'OUT',
   'date': '2017-07-01',
   'amount': None},
  {'player_id': 6624,
   'from_team_id': 11,
   'to_team_id': 36,
   'season_id': 853,
   'transfer': 'loan',
   'type': 'IN',
   'date': '2017-01-13',
   'amount': None},
  {'player_id': 177631,
   'from_team_id': 2945,
   'to_team_id': 36,
   'season_id': 2061,
   'transfer': 'n/a',
   'type': 'IN',
   'date': '2014-08-12',
   'amount': None},
  {'player_id': 27850,
   'from_team_id': 2394,
   'to_team_id': 36,
   'season_id': 8442,
   'transfer': 'bought',
   'type': 'IN',
   'date': '2017-07-15',
   'amount': '5M'},
  {'player_id': 260924,
   'from_team_id': 8137,
   'to_team_id': 36,
   'season_id': 8442,
   'transfer': 'bought',
   'type': 'IN',
   'date': '2017-07-01',
   'amount': '4.3M'},
  {'player_id': 32436,
   'from_team_id': 68,
   'to_team_id': 36,
   'season_id': 8442,
   'transfer': 'bought',
   'type': 'IN',
   'date': '2017-08-29',
   'amount': '13.5M'},
  {'player_id': 185450,
   'from_team_id': 36,
   'to_team_id': 618,
   'season_id': 2068,
   'transfer': 'free',
   'type': 'OUT',
   'date': '2008-07-01',
   'amount': None},
  {'player_id': 185450,
   'from_team_id': 676,
   'to_team_id': 36,
   'season_id': 2052,
   'transfer': 'n/a',
   'type': 'IN',
   'date': '2005-07-01',
   'amount': None},
  {'player_id': 186731,
   'from_team_id': 36,
   'to_team_id': 11354,
   'season_id': 8442,
   'transfer': 'n/a',
   'type': 'OUT',
   'date': '2017-07-20',
   'amount': None},
  {'player_id': 186731,
   'from_team_id': 93,
   'to_team_id': 36,
   'season_id': 2061,
   'transfer': 'n/a',
   'type': 'IN',
   'date': '2015-01-25',
   'amount': None},
  {'player_id': 186583,
   'from_team_id': 36,
   'to_team_id': 214,
   'season_id': 2063,
   'transfer': 'sold',
   'type': 'OUT',
   'date': '2015-07-04',
   'amount': '10M'},
  {'player_id': 108735,
   'from_team_id': 649,
   'to_team_id': 36,
   'season_id': 2060,
   'transfer': 'loan',
   'type': 'IN',
   'date': '2014-01-23',
   'amount': None},
  {'player_id': 187759,
   'from_team_id': 36,
   'to_team_id': 10246,
   'season_id': 2059,
   'transfer': 'free',
   'type': 'OUT',
   'date': '2012-12-28',
   'amount': None},
  {'player_id': 188029,
   'from_team_id': 36,
   'to_team_id': 13411,
   'season_id': 2071,
   'transfer': 'n/a',
   'type': 'OUT',
   'date': '2011-08-01',
   'amount': None},
  {'player_id': 188029,
   'from_team_id': 6721,
   'to_team_id': 36,
   'season_id': 2071,
   'transfer': 'n/a',
   'type': 'IN',
   'date': '2011-05-01',
   'amount': None},
  {'player_id': 35283,
   'from_team_id': 36,
   'to_team_id': 35,
   'season_id': 2070,
   'transfer': 'sold',
   'type': 'OUT',
   'date': '2010-02-19',
   'amount': '850K'},
  {'player_id': 186455,
   'from_team_id': 36,
   'to_team_id': 83,
   'season_id': 2061,
   'transfer': 'n/a',
   'type': 'OUT',
   'date': '2014-07-01',
   'amount': None},
  {'player_id': 186455,
   'from_team_id': 83,
   'to_team_id': 36,
   'season_id': 2060,
   'transfer': 'loan',
   'type': 'IN',
   'date': '2013-07-15',
   'amount': None},
  {'player_id': 185196,
   'from_team_id': 36,
   'to_team_id': 7746,
   'season_id': 2060,
   'transfer': 'n/a',
   'type': 'OUT',
   'date': '2014-01-30',
   'amount': None},
  {'player_id': 185196,
   'from_team_id': 1012,
   'to_team_id': 36,
   'season_id': 2071,
   'transfer': 'free',
   'type': 'IN',
   'date': '2011-08-16',
   'amount': None},
  {'player_id': 187145,
   'from_team_id': 36,
   'to_team_id': 618,
   'season_id': 8442,
   'transfer': 'n/a',
   'type': 'OUT',
   'date': '2017-07-01',
   'amount': None},
  {'player_id': 187145,
   'from_team_id': 618,
   'to_team_id': 36,
   'season_id': 853,
   'transfer': 'loan',
   'type': 'IN',
   'date': '2016-07-18',
   'amount': None},
  {'player_id': 189303,
   'from_team_id': 36,
   'to_team_id': 931,
   'season_id': 853,
   'transfer': 'free',
   'type': 'OUT',
   'date': '2016-07-01',
   'amount': None},
  {'player_id': 189303,
   'from_team_id': 36,
   'to_team_id': 8396,
   'season_id': 2063,
   'transfer': 'loan',
   'type': 'OUT',
   'date': '2015-07-09',
   'amount': None},
  {'player_id': 189303,
   'from_team_id': 28087,
   'to_team_id': 36,
   'season_id': 2059,
   'transfer': 'n/a',
   'type': 'IN',
   'date': '2012-07-01',
   'amount': None},
  {'player_id': 189303,
   'from_team_id': 36,
   'to_team_id': 28087,
   'season_id': 2059,
   'transfer': 'loan',
   'type': 'OUT',
   'date': '2012-02-01',
   'amount': None},
  {'player_id': 189303,
   'from_team_id': 25811,
   'to_team_id': 36,
   'season_id': 2071,
   'transfer': 'n/a',
   'type': 'IN',
   'date': '2012-01-31',
   'amount': None},
  {'player_id': 189303,
   'from_team_id': 36,
   'to_team_id': 25811,
   'season_id': 2071,
   'transfer': 'loan',
   'type': 'OUT',
   'date': '2011-09-13',
   'amount': None},
  {'player_id': 164,
   'from_team_id': 36,
   'to_team_id': 12,
   'season_id': 2067,
   'transfer': 'free',
   'type': 'OUT',
   'date': '2007-08-01',
   'amount': None},
  {'player_id': 164,
   'from_team_id': 629,
   'to_team_id': 36,
   'season_id': 2053,
   'transfer': 'n/a',
   'type': 'IN',
   'date': '2006-07-01',
   'amount': None},
  {'player_id': 164,
   'from_team_id': 629,
   'to_team_id': 36,
   'season_id': 2052,
   'transfer': 'loan',
   'type': 'IN',
   'date': '2005-08-01',
   'amount': None},
  {'player_id': 185944,
   'from_team_id': 36,
   'to_team_id': 377,
   'season_id': 2071,
   'transfer': 'free',
   'type': 'OUT',
   'date': '2011-08-12',
   'amount': None},
  {'player_id': 169518,
   'from_team_id': 36,
   'to_team_id': 2712,
   'season_id': 2061,
   'transfer': 'n/a',
   'type': 'OUT',
   'date': '2014-07-01',
   'amount': None},
  {'player_id': 169518,
   'from_team_id': 2712,
   'to_team_id': 36,
   'season_id': 2060,
   'transfer': 'loan',
   'type': 'IN',
   'date': '2014-01-31',
   'amount': None},
  {'player_id': 159742,
   'from_team_id': 36,
   'to_team_id': 7035,
   'season_id': 8442,
   'transfer': 'n/a',
   'type': 'OUT',
   'date': '2017-07-01',
   'amount': None},
  {'player_id': 159742,
   'from_team_id': 7035,
   'to_team_id': 36,
   'season_id': 853,
   'transfer': 'loan',
   'type': 'IN',
   'date': '2016-07-15',
   'amount': None},
  {'player_id': 129094,
   'from_team_id': 3427,
   'to_team_id': 36,
   'season_id': 2068,
   'transfer': 'loan',
   'type': 'IN',
   'date': '2008-08-01',
   'amount': None},
  {'player_id': 185393,
   'from_team_id': 3468,
   'to_team_id': 36,
   'season_id': 2067,
   'transfer': 'loan',
   'type': 'IN',
   'date': '2007-08-01',
   'amount': None},
  {'player_id': 188324,
   'from_team_id': 36,
   'to_team_id': 1886,
   'season_id': 2061,
   'transfer': 'n/a',
   'type': 'OUT',
   'date': '2014-07-01',
   'amount': None},
  {'player_id': 188324,
   'from_team_id': 1886,
   'to_team_id': 36,
   'season_id': 2059,
   'transfer': 'loan',
   'type': 'IN',
   'date': '2013-01-31',
   'amount': None},
  {'player_id': 186345,
   'from_team_id': 36,
   'to_team_id': 214,
   'season_id': 2061,
   'transfer': 'sold',
   'type': 'OUT',
   'date': '2014-07-31',
   'amount': '2M'},
  {'player_id': 186345,
   'from_team_id': 7031,
   'to_team_id': 36,
   'season_id': 2060,
   'transfer': 'n/a',
   'type': 'IN',
   'date': '2013-07-01',
   'amount': None},
  {'player_id': 186345,
   'from_team_id': 36,
   'to_team_id': 7031,
   'season_id': 2059,
   'transfer': 'loan',
   'type': 'OUT',
   'date': '2012-07-23',
   'amount': None},
  {'player_id': 185516,
   'from_team_id': 36,
   'to_team_id': 214,
   'season_id': 8442,
   'transfer': 'sold',
   'type': 'OUT',
   'date': '2017-07-01',
   'amount': '3M'},
  {'player_id': 185516,
   'from_team_id': 36,
   'to_team_id': 214,
   'season_id': 853,
   'transfer': 'loan',
   'type': 'OUT',
   'date': '2017-01-31',
   'amount': None},
  {'player_id': 185516,
   'from_team_id': 103,
   'to_team_id': 36,
   'season_id': 2059,
   'transfer': 'bought',
   'type': 'IN',
   'date': '2013-01-31',
   'amount': '1.2M'},
  {'player_id': 185516,
   'from_team_id': 103,
   'to_team_id': 36,
   'season_id': 2071,
   'transfer': 'loan',
   'type': 'IN',
   'date': '2011-08-30',
   'amount': None},
  {'player_id': 186657,
   'from_team_id': 36,
   'to_team_id': 126,
   'season_id': 2063,
   'transfer': 'sold',
   'type': 'OUT',
   'date': '2015-07-01',
   'amount': '500K'},
  {'player_id': 186657,
   'from_team_id': 618,
   'to_team_id': 36,
   'season_id': 2060,
   'transfer': 'bought',
   'type': 'IN',
   'date': '2013-07-01',
   'amount': '1M'},
  {'player_id': 187548,
   'from_team_id': 36,
   'to_team_id': 931,
   'season_id': 2069,
   'transfer': 'n/a',
   'type': 'OUT',
   'date': '2009-07-17',
   'amount': None},
  {'player_id': 186425,
   'from_team_id': 36,
   'to_team_id': 231,
   'season_id': 8442,
   'transfer': 'free',
   'type': 'OUT',
   'date': '2017-07-13',
   'amount': None},
  {'player_id': 186425,
   'from_team_id': 83,
   'to_team_id': 36,
   'season_id': 2061,
   'transfer': 'free',
   'type': 'IN',
   'date': '2014-07-06',
   'amount': None},
  {'player_id': 24098,
   'from_team_id': 36,
   'to_team_id': 676,
   'season_id': 2063,
   'transfer': 'free',
   'type': 'OUT',
   'date': '2015-07-01',
   'amount': None},
  {'player_id': 24098,
   'from_team_id': 293,
   'to_team_id': 36,
   'season_id': 2059,
   'transfer': 'bought',
   'type': 'IN',
   'date': '2012-08-22',
   'amount': '1M'},
  {'player_id': 1792,
   'from_team_id': 36,
   'to_team_id': 9,
   'season_id': 853,
   'transfer': 'sold',
   'type': 'OUT',
   'date': '2016-07-01',
   'amount': '18M'},
  {'player_id': 1792,
   'from_team_id': 605,
   'to_team_id': 36,
   'season_id': 2060,
   'transfer': 'bought',
   'type': 'IN',
   'date': '2013-07-01',
   'amount': '2.6M'},
  {'player_id': 186393,
   'from_team_id': 36,
   'to_team_id': 60,
   'season_id': 2059,
   'transfer': 'n/a',
   'type': 'OUT',
   'date': '2012-08-30',
   'amount': None},
  {'player_id': 186393,
   'from_team_id': 361,
   'to_team_id': 36,
   'season_id': 2071,
   'transfer': 'n/a',
   'type': 'IN',
   'date': '2011-08-01',
   'amount': None},
  {'player_id': 185019,
   'from_team_id': 36,
   'to_team_id': 3968,
   'season_id': 2053,
   'transfer': 'n/a',
   'type': 'OUT',
   'date': '2006-07-01',
   'amount': None},
  {'player_id': 185019,
   'from_team_id': 344,
   'to_team_id': 36,
   'season_id': None,
   'transfer': 'n/a',
   'type': 'IN',
   'date': '1999-07-01',
   'amount': None},
  {'player_id': 185609,
   'from_team_id': 36,
   'to_team_id': 676,
   'season_id': 2060,
   'transfer': 'n/a',
   'type': 'OUT',
   'date': '2013-07-01',
   'amount': None},
  {'player_id': 185609,
   'from_team_id': 676,
   'to_team_id': 36,
   'season_id': 2059,
   'transfer': 'loan',
   'type': 'IN',
   'date': '2012-07-05',
   'amount': None},
  {'player_id': 186946,
   'from_team_id': 36,
   'to_team_id': 7031,
   'season_id': 2059,
   'transfer': 'n/a',
   'type': 'OUT',
   'date': '2012-07-13',
   'amount': None},
  {'player_id': 186946,
   'from_team_id': 93,
   'to_team_id': 36,
   'season_id': 2071,
   'transfer': 'n/a',
   'type': 'IN',
   'date': '2011-08-31',
   'amount': None},
  {'player_id': 2920,
   'from_team_id': 36,
   'to_team_id': 344,
   'season_id': 8442,
   'transfer': 'free',
   'type': 'OUT',
   'date': '2017-08-18',
   'amount': None},
  {'player_id': 2920,
   'from_team_id': 361,
   'to_team_id': 36,
   'season_id': 8442,
   'transfer': 'n/a',
   'type': 'IN',
   'date': '2017-07-01',
   'amount': None},
  {'player_id': 2920,
   'from_team_id': 36,
   'to_team_id': 361,
   'season_id': 853,
   'transfer': 'loan',
   'type': 'OUT',
   'date': '2016-07-27',
   'amount': None},
  {'player_id': 2920,
   'from_team_id': 56,
   'to_team_id': 36,
   'season_id': 853,
   'transfer': 'n/a',
   'type': 'IN',
   'date': '2016-06-01',
   'amount': None},
  {'player_id': 2920,
   'from_team_id': 36,
   'to_team_id': 56,
   'season_id': 2063,
   'transfer': 'loan',
   'type': 'OUT',

In [11]:
seasons = pd.read_csv('../data/seasons.csv')
leagues = pd.read_csv('../data/leagues.csv')

In [13]:
leagues.loc[leagues['name'] == 'La Liga']['seasons']

26    [{'id': 2052, 'name': '2005/2006', 'league_id'...
Name: seasons, dtype: object

In [10]:
seasons.head()

,Unnamed: 0,current_round_id,current_stage_id,id,is_current_season,league_id,name
0,0,NaN,NaN,5307,False,2,2005/2006
1,1,NaN,NaN,5308,False,2,2006/2007
2,2,NaN,NaN,5309,False,2,2007/2008
3,3,NaN,NaN,5310,False,2,2008/2009
4,4,NaN,NaN,5311,False,2,2009/2010

In [82]:
countries = api.countries(includes=['continent', 'leagues'])
countries = pd.DataFrame(countries)
print(countries.shape)
countries.head()

(249, 5)

,continent,extra,id,leagues,name
0,"{'id': 1, 'name': 'Europe'}","{'continent': 'Europe', 'sub_region': 'Eastern...",2,[],Poland
1,"{'id': 7, 'name': 'South America'}","{'continent': 'Americas', 'sub_region': 'South...",5,[],Brazil
2,"{'id': 1, 'name': 'Europe'}","{'continent': 'Europe', 'sub_region': 'Western...",11,[],Germany
3,"{'id': 1, 'name': 'Europe'}","{'continent': 'Europe', 'sub_region': 'Western...",17,[],France
4,"{'id': 1, 'name': 'Europe'}","{'continent': 'Europe', 'sub_region': 'Souther...",20,[],Portugal

In [235]:
country_of_interest = 'Denmark'
country_id = countries.loc[countries['name'] == country_of_interest, 'id'].iloc[0]

In [236]:
leagues = api.leagues(includes=['country', 'seasons'])
leagues = pd.DataFrame(leagues)
leagues['country_name'] = leagues['country'].apply(lambda x: x['name'])
leagues['country_id'] = leagues['country'].apply(lambda x: x['id'])
print(leagues.shape)
leagues.head()

(4, 16)

,active,country,country_id,coverage,current_round_id,current_season_id,current_stage_id,id,is_cup,legacy_id,live_standings,logo_path,name,seasons,type,country_name
0,True,"{'id': 320, 'name': 'Denmark', 'extra': {'cont...",320,"{'predictions': 1, 'topscorer_goals': True, 't...",169500.0,16020,77443802.0,271,False,43.0,True,https://cdn.sportmonks.com/images/soccer/leagu...,Superliga,"[{'id': 1273, 'name': '2005/2006', 'league_id'...",domestic,Denmark
1,True,"{'id': 1161, 'name': 'Scotland', 'extra': {'co...",1161,"{'predictions': 1, 'topscorer_goals': True, 't...",173641.0,16222,77444704.0,501,False,66.0,True,https://cdn.sportmonks.com/images/soccer/leagu...,Premiership,"[{'id': 1927, 'name': '2005/2006', 'league_id'...",domestic,Scotland
2,True,"{'id': 1161, 'name': 'Scotland', 'extra': {'co...",1161,"{'predictions': 1, 'topscorer_goals': False, '...",NaN,15936,NaN,513,False,NaN,False,None,Premiership Play-Offs,"[{'id': 1951, 'name': '2013/2014', 'league_id'...",domestic,Scotland
3,True,"{'id': 320, 'name': 'Denmark', 'extra': {'cont...",320,"{'predictions': 1, 'topscorer_goals': True, 't...",NaN,15949,NaN,1659,False,NaN,False,None,Superliga Play-offs,"[{'id': 15949, 'name': '2018/2019', 'league_id...",domestic,Denmark

In [237]:
country_of_interest = 'Denmark'
ids_of_interest = leagues.loc[leagues['country_name'] == country_of_interest, ['id', 'name']].set_index('name')['id'].to_dict()
ids_of_interest

{'Superliga': 271, 'Superliga Play-offs': 1659}

In [240]:
league_of_interest = 'Superliga'
id_of_interest = ids_of_interest[league_of_interest]
seasons_of_interest = pd.DataFrame(leagues.loc[leagues['id'] == id_of_interest, 'seasons'].iloc[0])

In [241]:
seasons_of_interest

,current_round_id,current_stage_id,id,is_current_season,league_id,name
0,NaN,NaN,1273,False,271,2005/2006
1,NaN,NaN,1274,False,271,2006/2007
2,NaN,NaN,1275,False,271,2007/2008
3,NaN,NaN,1276,False,271,2008/2009
4,NaN,NaN,1277,False,271,2009/2010
5,NaN,NaN,1278,False,271,2010/2011
6,NaN,NaN,1279,False,271,2011/2012
7,NaN,NaN,1280,False,271,2012/2013
8,NaN,NaN,1281,False,271,2013/2014
9,NaN,NaN,1282,False,271,2014/2015
10,NaN,NaN,1286,False,271,2015/2016
11,NaN,NaN,759,False,271,2016/2017
12,NaN,NaN,6361,False,271,2017/2018
13,NaN,NaN,12919,False,271,2018/2019
14,169500.0,77443802.0,16020,True,271,2019/2020

In [243]:
#season_id = seasons_of_interest['id'].iloc[-2]
#fixtures = api.season_results(season_id, includes=['flatOdds'])
#fixtures = pd.DataFrame(fixtures)
#print(fixtures.shape)
#fixtures.head()

In [244]:
from datetime import datetime
start_date = datetime(2018, 7, 1)
end_date = datetime(2019, 7, 1)
fixture_data = api.fixtures(start_date, end_date, league_ids=[id_of_interest], includes=['flatOdds'])
fixture_data = pd.DataFrame(fixture_data)
print(fixture_data.shape)
fixture_data.head()

(243, 29)

,aggregate_id,assistants,attendance,coaches,colors,commentaries,deleted,details,flatOdds,formations,...,scores,season_id,stage_id,standings,time,venue_id,visitorteam_id,weather_report,winner_team_id,winning_odds_calculated
0,NaN,"{'first_assistant_id': 16959, 'second_assistan...",4168.0,"{'localteam_coach_id': 2510428, 'visitorteam_c...",None,None,False,None,"[{'bookmaker_id': 2, 'bookmaker_event_id': Non...","{'localteam_formation': '3-5-2', 'visitorteam_...",...,"{'localteam_score': 3, 'visitorteam_score': 1,...",12919,7088928,"{'localteam_position': 13, 'visitorteam_positi...","{'status': 'FT', 'starting_at': {'date_time': ...",4832.0,1703,"{'code': 'clear', 'type': 'clear sky', 'icon':...",7466.0,True
1,NaN,"{'first_assistant_id': 12878, 'second_assistan...",5122.0,"{'localteam_coach_id': 524555, 'visitorteam_co...",None,None,False,None,"[{'bookmaker_id': 2, 'bookmaker_event_id': Non...","{'localteam_formation': '4-4-2', 'visitorteam_...",...,"{'localteam_score': 0, 'visitorteam_score': 1,...",12919,7088928,"{'localteam_position': 12, 'visitorteam_positi...","{'status': 'FT', 'starting_at': {'date_time': ...",5653.0,1020,"{'code': 'clouds', 'type': 'few clouds', 'icon...",1020.0,True
2,NaN,"{'first_assistant_id': 12728, 'second_assistan...",NaN,"{'localteam_coach_id': 456421, 'visitorteam_co...",None,None,False,None,"[{'bookmaker_id': 1, 'bookmaker_event_id': '27...","{'localteam_formation': '3-4-3', 'visitorteam_...",...,"{'localteam_score': 0, 'visitorteam_score': 0,...",12919,7088928,"{'localteam_position': 8, 'visitorteam_positio...","{'status': 'FT', 'starting_at': {'date_time': ...",342.0,2905,"{'code': 'clear', 'type': 'clear sky', 'icon':...",NaN,True
3,NaN,"{'first_assistant_id': 12871, 'second_assistan...",2139.0,"{'localteam_coach_id': 458506, 'visitorteam_co...",None,None,False,None,"[{'bookmaker_id': 2, 'bookmaker_event_id': Non...","{'localteam_formation': '3-4-3', 'visitorteam_...",...,"{'localteam_score': 1, 'visitorteam_score': 1,...",12919,7088928,"{'localteam_position': 9, 'visitorteam_positio...","{'status': 'FT', 'starting_at': {'date_time': ...",1436.0,1371,"{'code': 'clouds', 'type': 'broken clouds', 'i...",NaN,True
4,NaN,"{'first_assistant_id': 12696, 'second_assistan...",NaN,"{'localteam_coach_id': 16845924, 'visitorteam_...",None,None,False,None,"[{'bookmaker_id': 2, 'bookmaker_event_id': Non...","{'localteam_formation': '4-1-4-1', 'visitortea...",...,"{'localteam_score': 3, 'visitorteam_score': 2,...",12919,7088928,"{'localteam_position': 12, 'visitorteam_positi...","{'status': 'FT', 'starting_at': {'date_time': ...",1608.0,1789,"{'code': 'clouds', 'type': 'few clouds', 'icon...",2706.0,True

In [279]:
fixture_data.iloc[0]

aggregate_id                                                             NaN
assistants                 {'first_assistant_id': 16959, 'second_assistan...
attendance                                                              4168
coaches                    {'localteam_coach_id': 2510428, 'visitorteam_c...
colors                                                                  None
commentaries                                                            None
deleted                                                                False
details                                                                 None
flatOdds                   [{'bookmaker_id': 2, 'bookmaker_event_id': Non...
formations                 {'localteam_formation': '3-5-2', 'visitorteam_...
group_id                                                                 NaN
id                                                                  10328708
league_id                                                                271
leg                                                                      1/1
localteam_id                                                            7466
neutral_venue                                                          False
pitch                                                                   None
referee_id                                                             15708
round_id                                                              147052
scores                     {'localteam_score': 3, 'visitorteam_score': 1,...
season_id                                                              12919
stage_id                                                             7088928
standings                  {'localteam_position': 13, 'visitorteam_positi...
time                       {'status': 'FT', 'starting_at': {'date_time': ...
venue_id                                                                4832
visitorteam_id                                                          1703
weather_report             {'code': 'clear', 'type': 'clear sky', 'icon':...
winner_team_id                                                          7466
winning_odds_calculated                                                 True
Name: 0, dtype: object

In [250]:
bookmakers = api.bookmakers()
bookmakers = pd.DataFrame(bookmakers)
bookmaker_of_interest = 'bet365'
bookmaker_id = bookmakers.loc[bookmakers['name'] == bookmaker_of_interest, 'id'].iloc[0]
market_id = 80

In [284]:
odds = []
for index, row in fixtures.iterrows():
    single_odd_data = [o['odds'] for o in row['flatOdds'] if (o['bookmaker_id'] == bookmaker_id) and (o['market_id'] == market_id)][0]
    odds.extend([{'odd_name': o['label'], 'odd_value': o['value'], 'odd_winning': o['winning'], 'id': row['id']} for o in single_odd_data])

odds = pd.DataFrame(odds)
odds.head()

         id odd_name odd_value odd_winning
0  10328703        1      3.75        True
1  10328703        X      2.50       False
2  10328703        2      2.20       False
3  10328704        1      1.90       False
4  10328704        X      2.75       False

In [288]:
fixture_and_odds = pd.merge(fixture_data, odds, on='id')
print(fixture_and_odds.shape)
fixture_and_odds.head()

(729, 32)

,aggregate_id,assistants,attendance,coaches,colors,commentaries,deleted,details,flatOdds,formations,...,standings,time,venue_id,visitorteam_id,weather_report,winner_team_id,winning_odds_calculated,odd_name,odd_value,odd_winning
0,NaN,"{'first_assistant_id': 16959, 'second_assistan...",4168.0,"{'localteam_coach_id': 2510428, 'visitorteam_c...",None,None,False,None,"[{'bookmaker_id': 2, 'bookmaker_event_id': Non...","{'localteam_formation': '3-5-2', 'visitorteam_...",...,"{'localteam_position': 13, 'visitorteam_positi...","{'status': 'FT', 'starting_at': {'date_time': ...",4832.0,1703,"{'code': 'clear', 'type': 'clear sky', 'icon':...",7466.0,True,1,2.87,True
1,NaN,"{'first_assistant_id': 16959, 'second_assistan...",4168.0,"{'localteam_coach_id': 2510428, 'visitorteam_c...",None,None,False,None,"[{'bookmaker_id': 2, 'bookmaker_event_id': Non...","{'localteam_formation': '3-5-2', 'visitorteam_...",...,"{'localteam_position': 13, 'visitorteam_positi...","{'status': 'FT', 'starting_at': {'date_time': ...",4832.0,1703,"{'code': 'clear', 'type': 'clear sky', 'icon':...",7466.0,True,X,2.30,False
2,NaN,"{'first_assistant_id': 16959, 'second_assistan...",4168.0,"{'localteam_coach_id': 2510428, 'visitorteam_c...",None,None,False,None,"[{'bookmaker_id': 2, 'bookmaker_event_id': Non...","{'localteam_formation': '3-5-2', 'visitorteam_...",...,"{'localteam_position': 13, 'visitorteam_positi...","{'status': 'FT', 'starting_at': {'date_time': ...",4832.0,1703,"{'code': 'clear', 'type': 'clear sky', 'icon':...",7466.0,True,2,3.00,False
3,NaN,"{'first_assistant_id': 12878, 'second_assistan...",5122.0,"{'localteam_coach_id': 524555, 'visitorteam_co...",None,None,False,None,"[{'bookmaker_id': 2, 'bookmaker_event_id': Non...","{'localteam_formation': '4-4-2', 'visitorteam_...",...,"{'localteam_position': 12, 'visitorteam_positi...","{'status': 'FT', 'starting_at': {'date_time': ...",5653.0,1020,"{'code': 'clouds', 'type': 'few clouds', 'icon...",1020.0,True,1,2.62,False
4,NaN,"{'first_assistant_id': 12878, 'second_assistan...",5122.0,"{'localteam_coach_id': 524555, 'visitorteam_co...",None,None,False,None,"[{'bookmaker_id': 2, 'bookmaker_event_id': Non...","{'localteam_formation': '4-4-2', 'visitorteam_...",...,"{'localteam_position': 12, 'visitorteam_positi...","{'status': 'FT', 'starting_at': {'date_time': ...",5653.0,1020,"{'code': 'clouds', 'type': 'few clouds', 'icon...",1020.0,True,X,2.37,False

In [289]:
fixture_and_odds.iloc[0]

aggregate_id                                                             NaN
assistants                 {'first_assistant_id': 16959, 'second_assistan...
attendance                                                              4168
coaches                    {'localteam_coach_id': 2510428, 'visitorteam_c...
colors                                                                  None
commentaries                                                            None
deleted                                                                False
details                                                                 None
flatOdds                   [{'bookmaker_id': 2, 'bookmaker_event_id': Non...
formations                 {'localteam_formation': '3-5-2', 'visitorteam_...
group_id                                                                 NaN
id                                                                  10328708
league_id                                                                271
leg                                                                      1/1
localteam_id                                                            7466
neutral_venue                                                          False
pitch                                                                   None
referee_id                                                             15708
round_id                                                              147052
scores                     {'localteam_score': 3, 'visitorteam_score': 1,...
season_id                                                              12919
stage_id                                                             7088928
standings                  {'localteam_position': 13, 'visitorteam_positi...
time                       {'status': 'FT', 'starting_at': {'date_time': ...
venue_id                                                                4832
visitorteam_id                                                          1703
weather_report             {'code': 'clear', 'type': 'clear sky', 'icon':...
winner_team_id                                                          7466
winning_odds_calculated                                                 True
odd_name                                                                   1
odd_value                                                               2.87
odd_winning                                                             True
Name: 0, dtype: object

In [296]:
# Downloading fixtures and odds for a given league

In [331]:
from configparser import ConfigParser
import pandas as pd
from datetime import datetime, date
import requests
from sportmonks.soccer import SoccerApiV2



def download_leagues(token, path='../data/leagues.csv'):
    api = SoccerApiV2(api_token=token)
    leagues = api.leagues(includes=['country', 'seasons'])
    leagues = pd.DataFrame(leagues)
    leagues['country_name'] = leagues['country'].apply(lambda x: x['name'])
    leagues['country_id'] = leagues['country'].apply(lambda x: x['id'])
    leagues.to_csv(path, index=False)

    
def download_bookmakers(token, path='../data/bookmakers.csv'):
    api = SoccerApiV2(api_token=token)
    bookmakers = api.bookmakers()
    bookmakers = pd.DataFrame(bookmakers)
    bookmakers.to_csv(path, index=False)

    
def load_leagues(path='../data/leagues.csv'):
    return pd.read_csv(path)


def load_bookmakers(path='../data/bookmakers.csv'):
    return pd.read_csv(path)


def get_league_id_from_name(league_data, league_name):
    return league_data.loc[league_data['name'] == league_name, 'id'].iloc[0]


def get_bet365_id(bookmaker_data):
    return bookmaker_data.loc[bookmaker_data['name'] == 'bet365', 'id'].iloc[0]


def download_fixtures_and_odds_single_league(token, league_name, start_date, end_date, path=None):
    league_data = load_leagues()
    league_id = get_league_id_from_name(league_data, league_name)
    
    api = SoccerApiV2(api_token=token)
    fixture_data = api.fixtures(start_date, end_date, league_ids=[league_id], includes=['flatOdds'])
    fixture_data = pd.DataFrame(fixture_data)
    odds = []
    bookmaker_data = load_bookmakers()
    bookmaker_id = get_bet365_id(bookmaker_data)
    for index, row in fixture_data.iterrows():
        try:
            single_odd_data = [o['odds'] for o in row['flatOdds'] if (o['bookmaker_id'] == bookmaker_id) and (o['market_id'] == MARKET_ID)][0]
        except IndexError: # No odd data 
            continue
        odds.extend([{'odd_name': o['label'], 'odd_value': o['value'], 'odd_winning': o['winning'], 'id': row['id']} for o in single_odd_data])

    odds = pd.DataFrame(odds)
    fixture_and_odds = pd.merge(fixture_data, odds, on='id', how='left')
    if path is None:
        path = f'../data/fixtures_and_odds_{league_name}_{str(start_date)}_{str(end_date)}.csv'
     
    fixture_and_odds.to_csv(path)
    print(f'Saved fixtures and odds for league {league_name}!')

def load_fixtures_and_odds(path):
    return pd.read_csv(path)
    
parser = ConfigParser()
parser.read('../config.cfg')
token = parser.get('sportmonks', 'token')

league_name = 'Superliga'
start_date = date(2015, 7, 1)
end_date = date(2019, 7, 1)
MARKET_ID = 80

#download_leagues(token, path='../data/leagues.csv')
#download_bookmakers(token, path='../data/bookmakers.csv')
download_fixtures_and_odds_single_league(token, league_name, start_date, end_date)

Saved fixtures and odds for league 271!

In [332]:
fixtures_and_odds = load_fixtures_and_odds(f'../data/fixtures_and_odds_{league_name}_{str(start_date)}_{str(end_date)}.csv')

In [42]:
### Other

In [49]:
team_data = pd.read_csv('../data/teams_league_La Liga.csv')

In [50]:
team_data.head()

,country_id,current_season_id,founded,id,legacy_id,logo_path,name,national_team,short_code,transfers,twitter,venue_id,season_id
0,32,16326,1923,36,290.0,https://cdn.sportmonks.com/images//soccer/team...,Celta de Vigo,False,CLV,"[{'player_id': 445429, 'from_team_id': 36, 'to...",@RCCelta,9239,2052
1,32,16326,1899,83,130.0,https://cdn.sportmonks.com/images//soccer/team...,Barcelona,False,FCB,"[{'player_id': 23746, 'from_team_id': 83, 'to_...",@FCBarcelona,9236,2052
2,32,16326,1983,106,295.0,https://cdn.sportmonks.com/images//soccer/team...,Getafe,False,GET,"[{'player_id': 125254, 'from_team_id': 106, 't...",@GetafeCF,9351,2052
3,32,13150,1948,126,288.0,https://cdn.sportmonks.com/images//soccer/team...,Málaga,False,MLA,"[{'player_id': 189999, 'from_team_id': 126, 't...",@MalagaCF,9233,2052
4,32,16326,1919,214,287.0,https://cdn.sportmonks.com/images//soccer/team...,Valencia,False,VAL,"[{'player_id': 447706, 'from_team_id': 214, 't...",@valenciacf,9240,2052

In [51]:
team_data['season_id'].unique()

array([ 2052,  2053,  2054,  2055,  2058,  2056,  2057,  2059,  2060,
        2061,  2063,   853,  8442, 13133, 16326])

In [ ]:
pd.DataFrame(eval(team_data.loc[(team_data['season_id'] == team_data['season_id'].max())
              & (team_data['name'] == 'Barcelona')]['transfers'].iloc[0])).sort_values('date')

In [69]:
pd.DataFrame(eval(team_data.loc[(team_data['season_id'] == team_data['season_id'].max())
              & (team_data['name'] == 'Barcelona')]['transfers'].iloc[0])).sort_values('date')

,amount,date,from_team_id,player_id,season_id,to_team_id,transfer,type
361,2.5M,1995-08-01,58,127924,NaN,83,bought,IN
363,14.5M,1998-07-01,83,185051,NaN,43,sold,OUT
39,15M,1999-07-01,58,184938,NaN,83,bought,IN
364,2.1M,2000-07-01,83,185427,NaN,126,sold,OUT
362,None,2000-07-01,43,185051,NaN,83,loan,IN
360,58.5M,2000-08-01,83,127924,NaN,3468,sold,OUT
21,None,2000-08-01,83,307,NaN,591,free,OUT
292,24.3M,2001-07-01,10002,108840,NaN,83,bought,IN
38,12M,2001-07-01,83,184938,NaN,605,sold,OUT
54,750K,2002-07-01,83,38,NaN,3477,sold,OUT
279,None,2002-07-01,83,24989,NaN,13304,loan,OUT
296,11M,2002-11-26,587,184890,NaN,83,bought,IN
295,None,2003-07-01,83,184890,NaN,3477,loan,OUT
329,None,2003-07-01,361,55900,NaN,83,loan,IN
312,32.3M,2003-08-01,591,128252,NaN,83,bought,IN
65,6.4M,2003-08-01,58,4035,NaN,83,bought,IN
322,5.3M,2003-08-01,6789,129443,NaN,83,bought,IN
36,3.2M,2003-08-16,83,510,NaN,19,sold,OUT
278,None,2004-01-01,83,24989,NaN,6827,loan,OUT
77,None,2004-02-04,83,185149,NaN,3169,loan,OUT
291,None,2004-07-01,83,108840,NaN,6789,loan,OUT
127,None,2004-07-01,83,184884,NaN,3457,loan,OUT
277,None,2004-07-02,83,24989,NaN,6623,free,OUT
72,27M,2004-08-01,645,4119,NaN,83,bought,IN
64,6M,2004-08-01,83,4035,NaN,652,sold,OUT
7,7M,2004-08-01,6789,94676,NaN,83,bought,IN
44,6.5M,2005-01-01,10002,128532,NaN,83,bought,IN
365,None,2005-07-01,83,187422,2052.0,10008,n/a,OUT
290,None,2005-07-01,6789,108840,2052.0,83,n/a,IN
76,None,2005-07-01,83,185149,2052.0,645,loan,OUT
...,...,...,...,...,...,...,...,...
484,None,2019-07-01,83,537593,16326.0,3781,free,OUT
477,3.3M,2019-07-01,2345,2846904,16326.0,83,bought,IN
481,26M,2019-07-01,214,128798,16326.0,83,bought,IN
468,12M,2019-07-01,3427,221615,16326.0,83,bought,IN
467,75M,2019-07-01,629,26536,16326.0,83,bought,IN
434,25M,2019-07-01,83,159372,16326.0,13,sold,OUT
469,12.9M,2019-07-01,83,4439,16326.0,36,sold,OUT
454,None,2019-07-01,26457,537632,16326.0,83,n/a,IN
425,None,2019-07-01,429,186944,16326.0,83,n/a,IN
422,None,2019-07-01,365,186613,16326.0,83,n/a,IN
447,21M,2019-07-01,83,186095,16326.0,68,sold,OUT
460,None,2019-07-01,289,529856,NaN,83,free,IN
93,None,2019-07-01,83,129818,16326.0,214,n/a,OUT
465,None,2019-07-01,83,702,16326.0,2714,n/a,OUT
420,2.5M,2019-07-01,83,188155,16326.0,459,sold,OUT
489,None,2019-07-02,83,221615,16326.0,485,sold,OUT
482,2M,2019-07-05,83,190239,16326.0,108,sold,OUT
485,120M,2019-07-12,7980,185658,16326.0,83,bought,IN
487,None,2019-07-12,83,186944,16326.0,1012,free,OUT
486,None,2019-07-14,83,23269735,16326.0,747,n/a,OUT
490,None,2019-07-16,83,6600012,16326.0,528,n/a,OUT
488,4M,2019-07-16,60,448448,16326.0,83,bought,IN
492,None,2019-07-18,83,448448,16326.0,106,loan,OUT
494,None,2019-07-27,83,186613,16326.0,554,free,OUT
495,None,2019-07-27,83,558,16326.0,3867,free,OUT
496,40M,2019-08-02,83,96633,16326.0,2963,sold,OUT
497,18M,2019-08-04,485,449187,16326.0,83,bought,IN
475,None,2020-07-01,83,10948339,NaN,3496,n/a,OUT
491,None,2020-07-01,106,448448,NaN,83,n/a,IN
379,None,2020-07-01,3702,185917,NaN,83,n/a,IN

In [72]:
api.player(127924)

{'player_id': 127924,
 'team_id': 123,
 'country_id': 20,
 'position_id': 3,
 'common_name': 'Luis Figo',
 'fullname': 'Luis Filipe Madeira Caeiro Figo',
 'firstname': 'Luis Filipe',
 'lastname': 'Madeira Caeiro Figo',
 'nationality': 'Portugal',
 'birthdate': '11/4/1972',
 'birthcountry': 'Portugal',
 'birthplace': 'Lisbon',
 'height': '180 cm',
 'weight': '75 kg',
 'image_path': 'https://cdn.sportmonks.com/images/soccer/players/20/127924.png'}

In [61]:
eval(team_data['transfers'].iloc[0])['player_id']

TypeError: list indices must be integers or slices, not str

In [43]:
seasons = pd.read_csv('../data/seasons.csv')
leagues = pd.read_csv('../data/leagues.csv')

In [53]:
[x['id'] for x in eval(leagues.loc[leagues['name'] == 'La Liga']['seasons'].iloc[0])]

[2052,
 2053,
 2054,
 2055,
 2058,
 2056,
 2057,
 2059,
 2060,
 2061,
 2063,
 853,
 8442,
 13133,
 16326]

In [29]:
season_id = seasons.iloc[-1]['id']
print(season_id)

15998

In [ ]:
def download_standings_single_league(token, league_name, base_path='data'):
    api = SoccerApiV2(api_token=token)
    leagues = pd.read_csv(base_path+'/leagues.csv')
    seasons = leagues.loc[leagues['name'] == league_name]['seasons'].iloc[0]
    all_standings = []
    for season in seasons:
        standings = api.standings(season_id=season)
        standings['season_id'] = season
        all_standings.extend(standings)
    
    pd.DataFrame(all_standings).to_csv(base_path+f'/standings_{league_name}.csv')

In [54]:
standings = api.standings(season_id=2052)

In [55]:
standings

[{'name': 'Regular Season',
  'league_id': 564,
  'season_id': 2052,
  'round_id': 54735,
  'round_name': 38,
  'type': 'Group Stage',
  'stage_id': 3356,
  'stage_name': 'Regular Season',
  'resource': 'stage',
  'standings': [{'position': 1,
    'team_id': 83,
    'team_name': 'Barcelona',
    'round_id': 54735,
    'round_name': 38,
    'group_id': None,
    'group_name': None,
    'overall': {'games_played': 38,
     'won': 25,
     'draw': 7,
     'lost': 6,
     'goals_scored': 80,
     'goals_against': 35},
    'home': {'games_played': 19,
     'won': 15,
     'draw': 3,
     'lost': 1,
     'goals_scored': 45,
     'goals_against': 15},
    'away': {'games_played': 19,
     'won': 10,
     'draw': 4,
     'lost': 5,
     'goals_scored': 35,
     'goals_against': 20},
    'total': {'goal_difference': '+45', 'points': 82},
    'result': None,
    'points': 82,
    'recent_form': 'LLWWW',
    'status': 'same'},
   {'position': 2,
    'team_id': 3468,
    'team_name': 'Real Madrid',
    'round_id': 54735,
    'round_name': 38,
    'group_id': None,
    'group_name': None,
    'overall': {'games_played': 38,
     'won': 20,
     'draw': 10,
     'lost': 8,
     'goals_scored': 70,
     'goals_against': 40},
    'home': {'games_played': 19,
     'won': 11,
     'draw': 4,
     'lost': 4,
     'goals_scored': 40,
     'goals_against': 21},
    'away': {'games_played': 19,
     'won': 9,
     'draw': 6,
     'lost': 4,
     'goals_scored': 30,
     'goals_against': 19},
    'total': {'goal_difference': '+30', 'points': 70},
    'result': None,
    'points': 70,
    'recent_form': 'LDWWW',
    'status': 'same'},
   {'position': 3,
    'team_id': 214,
    'team_name': 'Valencia',
    'round_id': 54735,
    'round_name': 38,
    'group_id': None,
    'group_name': None,
    'overall': {'games_played': 38,
     'won': 19,
     'draw': 12,
     'lost': 7,
     'goals_scored': 58,
     'goals_against': 33},
    'home': {'games_played': 19,
     'won': 10,
     'draw': 8,
     'lost': 1,
     'goals_scored': 34,
     'goals_against': 16},
    'away': {'games_played': 19,
     'won': 9,
     'draw': 4,
     'lost': 6,
     'goals_scored': 24,
     'goals_against': 17},
    'total': {'goal_difference': '+25', 'points': 69},
    'result': None,
    'points': 69,
    'recent_form': 'LDLWW',
    'status': 'same'},
   {'position': 4,
    'team_id': 676,
    'team_name': 'Sevilla',
    'round_id': 54735,
    'round_name': 38,
    'group_id': None,
    'group_name': None,
    'overall': {'games_played': 38,
     'won': 20,
     'draw': 8,
     'lost': 10,
     'goals_scored': 54,
     'goals_against': 39},
    'home': {'games_played': 19,
     'won': 12,
     'draw': 5,
     'lost': 2,
     'goals_scored': 29,
     'goals_against': 15},
    'away': {'games_played': 19,
     'won': 8,
     'draw': 3,
     'lost': 8,
     'goals_scored': 25,
     'goals_against': 24},
    'total': {'goal_difference': '+15', 'points': 68},
    'result': None,
    'points': 68,
    'recent_form': 'WWWWW',
    'status': 'same'},
   {'position': 5,
    'team_id': 459,
    'team_name': 'Osasuna',
    'round_id': 54735,
    'round_name': 38,
    'group_id': None,
    'group_name': None,
    'overall': {'games_played': 38,
     'won': 21,
     'draw': 5,
     'lost': 12,
     'goals_scored': 49,
     'goals_against': 43},
    'home': {'games_played': 19,
     'won': 12,
     'draw': 3,
     'lost': 4,
     'goals_scored': 28,
     'goals_against': 20},
    'away': {'games_played': 19,
     'won': 9,
     'draw': 2,
     'lost': 8,
     'goals_scored': 21,
     'goals_against': 23},
    'total': {'goal_difference': '+6', 'points': 68},
    'result': None,
    'points': 68,
    'recent_form': 'WLWLW',
    'status': 'same'},
   {'position': 6,
    'team_id': 36,
    'team_name': 'Celta de Vigo',
    'round_id': 54735,
    'round_name': 38,
    'group_id': None,
    'group_name': None,
    'overall': {'games_played': 38,
     'won': 20,
     'draw': 4,
     'lost': 14,
     'goals_scored': 45,
     'goals_against': 33},
    'home': {'games_played': 19,
     'won': 13,
     'draw': 0,
     'lost': 6,
     'goals_scored': 25,
     'goals_against': 13},
    'away': {'games_played': 19,
     'won': 7,
     'draw': 4,
     'lost': 8,
     'goals_scored': 20,
     'goals_against': 20},
    'total': {'goal_difference': '+12', 'points': 64},
    'result': None,
    'points': 64,
    'recent_form': 'WDLWW',
    'status': 'same'},
   {'position': 7,
    'team_id': 3477,
    'team_name': 'Villarreal',
    'round_id': 54735,
    'round_name': 38,
    'group_id': None,
    'group_name': None,
    'overall': {'games_played': 38,
     'won': 14,
     'draw': 15,
     'lost': 9,
     'goals_scored': 50,
     'goals_against': 39},
    'home': {'games_played': 19,
     'won': 9,
     'draw': 6,
     'lost': 4,
     'goals_scored': 28,
     'goals_against': 18},
    'away': {'games_played': 19,
     'won': 5,
     'draw': 9,
     'lost': 5,
     'goals_scored': 22,
     'goals_against': 21},
    'total': {'goal_difference': '+11', 'points': 57},
    'result': None,
    'points': 57,
    'recent_form': 'WDWDL',
    'status': 'same'},
   {'position': 8,
    'team_id': 429,
    'team_name': 'Deportivo La Coruña',
    'round_id': 54735,
    'round_name': 38,
    'group_id': None,
    'group_name': None,
    'overall': {'games_played': 38,
     'won': 15,
     'draw': 10,
     'lost': 13,
     'goals_scored': 47,
     'goals_against': 45},
    'home': {'games_played': 19,
     'won': 6,
     'draw': 5,
     'lost': 8,
     'goals_scored': 19,
     'goals_against': 22},
    'away': {'games_played': 19,
     'won': 9,
     'draw': 5,
     'lost': 5,
     'goals_scored': 28,
     'goals_against': 23},
    'total': {'goal_difference': '+2', 'points': 55},
    'result': None,
    'points': 55,
    'recent_form': 'LLWLD',
    'status': 'same'},
   {'position': 9,
    'team_id': 106,
    'team_name': 'Getafe',
    'round_id': 54735,
    'round_name': 38,
    'group_id': None,
    'group_name': None,
    'overall': {'games_played': 38,
     'won': 15,
     'draw': 9,
     'lost': 14,
     'goals_scored': 54,
     'goals_against': 49},
    'home': {'games_played': 19,
     'won': 8,
     'draw': 7,
     'lost': 4,
     'goals_scored': 32,
     'goals_against': 24},
    'away': {'games_played': 19,
     'won': 7,
     'draw': 2,
     'lost': 10,
     'goals_scored': 22,
     'goals_against': 25},
    'total': {'goal_difference': '+5', 'points': 54},
    'result': None,
    'points': 54,
    'recent_form': 'LWLDW',
    'status': 'same'},
   {'position': 10,
    'team_id': 7980,
    'team_name': 'Atlético Madrid',
    'round_id': 54735,
    'round_name': 38,
    'group_id': None,
    'group_name': None,
    'overall': {'games_played': 38,
     'won': 13,
     'draw': 13,
     'lost': 12,
     'goals_scored': 45,
     'goals_against': 37},
    'home': {'games_played': 19,
     'won': 7,
     'draw': 6,
     'lost': 6,
     'goals_scored': 21,
     'goals_against': 18},
    'away': {'games_played': 19,
     'won': 6,
     'draw': 7,
     'lost': 6,
     'goals_scored': 24,
     'goals_against': 19},
    'total': {'goal_difference': '+8', 'points': 52},
    'result': None,
    'points': 52,
    'recent_form': 'DDLLW',
    'status': 'same'},
   {'position': 11,
    'team_id': 3968,
    'team_name': 'Real Zaragoza',
    'round_id': 54735,
    'round_name': 38,
    'group_id': None,
    'group_name': None,
    'overall': {'games_played': 38,
     'won': 10,
     'draw': 16,
     'lost': 12,
     'goals_scored': 46,
     'goals_against': 51},
    'home': {'games_played': 19,
     'won': 6,
     'draw': 6,
     'lost': 7,
     'goals_scored': 26,
     'goals_against': 26},
    'away': {'games_played': 19,
     'won': 4,
     'draw': 10,
     'lost': 5,
     'goals_scored': 20,
     'goals_against': 25},
    'total': {'goal_difference': -5, 'points': 46},
    'result': None,
    'points': 46,
    'recent_form': 'LWLDL',
    'status': 'same'},
   {'position': 12,
    'team_id': 13258,
    'team_name': 'Athletic Club',
    'round_id': 54735,
    'round_name': 38,
    'group_id': None,
    'group_name': None,
    'overall': {'games_played': 38,
     'won': 11,
     'draw': 12,
     'lost': 15,
     'goals_scored': 40,
     'goals_against': 46},
    'home': {'games_played': 19,
     'won': 7,
     'draw': 6,
     'lost': 6,
     'goals_scored': 19,
     'goals_against': 18},
    'away': {'games_played': 19,
     'won': 4,
     'draw': 6,
     'lost': 9,
     'goals_scored': 21,
     'goals_against': 28},
    'total': {'goal_difference': -6, 'points': 45},
    'result': None,
    'points': 45,
    'recent_form': 'WWWDL',
    'status': 'same'},
   {'position': 13,
    'team_id': 645,
    'team_name': 'Mallorca',
    'round_id': 54735,
    'round_name': 38,
    'group_id': None,
    'group_name': None,
    'overall': {'games_played': 38,
     'won': 10,
     'draw': 13,
     'lost': 15,
     'goals_scored': 37,
     'goals_against': 51},
    'home': {'games_played': 19,
     'won': 6,
     'draw': 8,
     'lost': 5,
     'goals_scored': 21,
     'goals_against': 21},
    'away': {'games_played': 19,
     'won': 4,
     'draw': 5,
     'lost': 10,
     'goals_scored': 16,
     'goals_against': 30},
    'total': {'goal_difference': -14, 'points': 43},
    'result': None,
    'points': 43,
    'recent_form': 'WLWWL',
    'status': 'same'},
   {'position': 14,
    'team_id': 485,
    'team_name': 'Real Betis',
    'round_id': 54735,
    'round_name': 38,
    'group_id': None,
    'group_name': None,
    'overall': {'games_played': 38,
     'won': 10,
     'draw': 12,
     'lost': 16,
     'goals_scored': 34,
     'goals_against': 51},
    'home': {'games_played': 19,
     'won': 8,
     'draw': 5,
     'lost': 6,
     'goals_scored': 19,
     'goals_against': 19},
    'away': {'games_played': 19,
     'won': 2,
     'draw': 7,
     'lost': 10,
     'goals_scored': 15,
     'goals_against': 32},
    'total': {'goal_difference': -17, 'points': 42},
    'result': None,
    'points': 42,
    'recent_form': 'DWLDL',
    'status': 'same'},
   {'position': 15,
    'team_id': 528,
    'team_name': 'Espanyol',
    'round_id': 54735,
    'round_name': 38,
    'group_id': None,
    'group_name': None,
    'overall': {'games_played': 38,
     'won': 10,
     'draw': 11,
     'lost': 17,
     'goals_scored': 36,
     'goals_against': 56},
    'home': {'games_played': 19,
     'won': 7,
     'draw': 4,
     'lost': 8,
     'goals_scored': 26,
     'goals_against': 24},
    'away': {'games_played': 19,
     'won': 3,
     'draw': 7,
     'lost': 9,
     'goals_scored': 10,
     'goals_against': 32},
    'total': {'goal_difference': -20, 'points': 41},
    'result': None,
    'points': 41,
    'recent_form': 'WLLDW',
    'status': 'same'},
   {'position': 16,
    'team_id': 9818,
    'team_name': 'Racing Santander',
    'round_id': 54735,
    'round_name': 38,
    'group_id': None,
    'group_name': None,
    'overall': {'games_played': 38,
     'won': 9,
     'draw': 13,
     'lost': 16,
     'goals_scored': 36,
     'goals_against': 49},
    'home': {'games_played': 19,
     'won': 4,
     'draw': 6,
     'lost': 9,
     'goals_scored': 18,
     'goals_against': 26},
    'away': {'games_played': 19,
     'won': 5,
     'draw': 7,
     'lost': 7,
     'goals_scored': 18,
     'goals_against': 23},
    'total': {'goal_difference': -13, 'points': 40},
    'result': None,
    'points': 40,
    'recent_form': 'LWLWL',
    'status': 'same'},
   {'position': 17,
    'team_id': 594,
    'team_name': 'Real Sociedad',
    'round_id': 54735,
    'round_name': 38,
    'group_id': None,
    'group_name': None,
    'overall': {'games_played': 38,
     'won': 11,
     'draw': 7,
     'lost': 20,
     'goals_scored': 48,
     'goals_against': 65},
    'home': {'games_played': 19,
     'won': 8,
     'draw': 4,
     'lost': 7,
     'goals_scored': 31,
     'goals_against': 27},
    'away': {'games_played': 19,
     'won': 3,
     'draw': 3,
     'lost': 13,
     'goals_scored': 17,
     'goals_against': 38},
    'total': {'goal_difference': -17, 'points': 40},
    'result': None,
    'points': 40,
    'recent_form': 'LDDLW',
    'status': 'same'},
   {'position': 18,
    'team_id': 2975,
    'team_name': 'Deportivo Alavés',
    'round_id': 54735,
    'round_name': 38,
    'group_id': None,
    'group_name': None,
    'overall': {'games_played': 38,
     'won': 9,
     'draw': 12,
     'lost': 17,
     'goals_scored': 35,
     'goals_against': 54},
    'home': {'games_played': 19,
     'won': 6,
     'draw': 6,
     'lost': 7,
     'goals_scored': 20,
     'goals_against': 24},
    'away': {'games_played': 19,
     'won': 3,
     'draw': 6,
     'lost': 10,
     'goals_scored': 15,
     'goals_against': 30},
    'total': {'goal_difference': -19, 'points': 39},
    'result': None,
    'points': 39,
    'recent_form': 'WLWLL',
    'status': 'same'},
   {'position': 19,
    'team_id': 6827,
    'team_name': 'Cádiz',
    'round_id': 54735,
    'round_name': 38,
    'group_id': None,
    'group_name': None,
    'overall': {'games_played': 37,
     'won': 7,
     'draw': 12,
     'lost': 18,
     'goals_scored': 31,
     'goals_against': 52},
    'home': {'games_played': 18,
     'won': 3,
     'draw': 8,
     'lost': 7,
     'goals_scored': 17,
     'goals_against': 25},
    'away': {'games_played': 19,
     'won': 4,
     'draw': 4,
     'lost': 11,
     'goals_scored': 14,
     'goals_against': 27},
    'total': {'goal_difference': -21, 'points': 33},
    'result': None,
    'points': 33,
    'recent_form': 'LDLDW',
    'status': 'same'},
   {'position': 20,
    'team_id': 126,
    'team_name': 'Málaga',
    'round_id': 54735,
    'round_name': 38,
    'group_id': None,
    'group_name': None,
    'overall': {'games_played': 37,
     'won': 5,
     'draw': 9,
     'lost': 23,
     'goals_scored': 36,
     'goals_against': 63},
    'home': {'games_played': 19,
     'won': 3,
     'draw': 5,
     'lost': 11,
     'goals_scored': 16,
     'goals_against': 25},
    'away': {'games_played': 18,
     'won': 2,
     'draw': 4,
     'lost': 12,
     'goals_scored': 20,
     'goals_against': 38},
    'total': {'goal_difference': -27, 'points': 24},
    'result': None,
    'points': 24,
    'recent_form': 'LLLLD',
    'status': 'same'}]}]

In [39]:
api

'https://soccer.sportmonks.com/api/v2.0'